#!/bin/bash
echo $SERVERS;
echo $B_QUERY_FUNS;
echo $CONFIG;

umask 000;
tpch_client/src/main/main --config=$CONFIG --data_folder=$DATA_FOLDER --global_index=$GLOBAL_INDEX --query_clients=$QUERY_CLIENTS --single_index_server=$SINGLE_INDEX_SERVER --test_name=$TEST_NAME --upd_rate=$UPD_RATE --reset=$RESET --id=$ID --split_updates=$SPLIT_UPDATES --split_updates_no_wait=$SPLIT_UPDATES_NO_WAIT --n_reads_txn=$N_READS_TXN --batch_mode=$BATCH_MODE --latency_mode=$LATENCY_MODE --servers=$SERVERS --use_top_sum=$USE_TOP_SUM --local_mode=$LOCAL_MODE --scale=$SF --non_random_servers=$NON_RANDOM_SERVERS --local_region_only=$LOCAL_REGION_ONLY --q15_size=$Q15_SIZE --update_specific_index=$UPDATE_SPECIFIC_INDEX --initialMem=$INITIAL_MEM --tpch_add_rate=$TPCH_ADD_RATE --is_bench=$IS_BENCH --b_nkeys=$B_N_KEYS --b_keys_type=$B_KEY_TYPE --b_add_rate=$B_ADD_RATE --b_part_read_rate=$B_PART_READ_RATE --b_query_rates=$B_QUERY_RATES --b_ops_per_txn=$B_OPS_PER_TXN --b_txns_before_wait=$B_TXNS_BEFORE_WAIT --b_nelems=$B_N_ELEMS --b_max_score=$B_MAX_SCORE --b_max_id=$B_MAX_ID --b_top_above=$B_TOP_ABOVE --b_top_n=$B_TOP_N --b_rnd_size=$B_RND_SIZE --b_min_change=$B_MIN_CHANGE --b_max_change=$B_MAX_CHANGE --b_max_sum=$B_MAX_SUM --b_max_nAdds=$B_MAX_N_ADDS --b_crdt_type=$B_CRDT_TYPE --b_query_funcs=$B_QUERY_FUNS --b_update_funcs=$B_UPDATE_FUNS --b_do_preload=$B_DO_PRELOAD --b_do_query=$B_DO_QUERY;
#--p_n_protos=$P_N_PROTOS --p_n_bytes=$P_N_BYTES --p_n_routines=$P_N_ROUTINES --p_n_mode=$P_N_MODE;

#tpch_client/src/main/main --config=$CONFIG --global_index=$GLOBAL_INDEX --query_clients=$QUERY_CLIENTS --single_index_server=$SINGLE_INDEX_SERVER --test_name=$TEST_NAME --upd_rate=$UPD_RATE --reset=$RESET --id=$ID --split_updates=$SPLIT_UPDATES --split_updates_no_wait=$SPLIT_UPDATES_NO_WAIT --n_reads_txn=$N_READS_TXN --batch_mode=$BATCH_MODE --latency_mode=$LATENCY_MODE --servers=$SERVERS --use_top_sum=$USE_TOP_SUM --local_mode=$LOCAL_MODE --scale=$SF --non_random_servers=$NON_RANDOM_SERVERS --local_region_only=$LOCAL_REGION_ONLY --q15_size=$Q15_SIZE --update_specific_index=$UPDATE_SPECIFIC_INDEX;